"""Write data/recipes-db/gi_sources.py — one provenance record per ingredient GI value.

Source-of-truth policy (v1, 2026-09-26):
  1. Supplemental Table 1 of the 2021 International Tables (ISO 26642:2010-compliant) when n >= 2  -> confidence "high"
  2. Otherwise the median of ISO + method-deviation entries                                        -> "medium"
  3. Otherwise the University of Sydney online database                                            -> "medium"
  4. No measured value anywhere -> conventional placeholder, confidence "none (placeholder)"
Nutrients always come from USDA FoodData Central and are unaffected.
"""
import json, os, sys, statistics, re
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "recipes-db"))
sys.path.insert(0, os.path.dirname(__file__))
from ingredients import ING
import resolve_gi as R   # runs the resolver and writes gi_provenance.json

CIT_INTL = ("Atkinson FS, Brand-Miller JC, Foster-Powell K, Buyken AE, Goletzke J. International tables of "
            "glycemic index and glycemic load values 2021. Am J Clin Nutr 2021;114(5):1625-32. doi:10.1093/ajcn/nqab233")
CIT_SYD  = "University of Sydney GI database, glycemicindex.com/gi-search (accessed 2026-09-16)"
CIT_USDA = "USDA FoodData Central (SR Legacy / Foundation Foods), fdc.nal.usda.gov"

prov = json.load(open(os.path.join(os.path.dirname(__file__), "gi_provenance.json")))
by = {p["key"]: p for p in prov}
out = {}
for key, v in ING.items():
    name, kcal, p_, f_, c_, fib, gi, group = v
    rec = {"gi": gi, "nutrients_source": CIT_USDA, "checked": "2026-09-26"}
    p = by.get(key)
    if gi == 0 and group in ("protein", "seafood", "egg", "dairy", "fat", "drink", "spice", "pantry", "condiment", "veg") and c_ - fib <= 0.6:
        rec.update(gi_source="No available carbohydrate — GI is 0 by definition (protein / fat / water)",
                   evidence="n/a", confidence="definitional", citation="ISO 26642:2010")
    elif p and p["iso"] and p["iso"]["n"] >= 2:
        s = p["iso"]
        rec.update(gi_source="2021 International Tables, Suppl. Table 1 (ISO 26642:2010-compliant studies)",
                   evidence=f'median of {s["n"]} tested foods, range {s["min"]:g}-{s["max"]:g}',
                   confidence="high", citation=CIT_INTL, measured_median=s["median"])
    elif p and (p["iso"] or p["deviation"]):
        a, b = p["iso"], p["deviation"]
        n = (a["n"] if a else 0) + (b["n"] if b else 0)
        lo = min([x["min"] for x in (a, b) if x]); hi = max([x["max"] for x in (a, b) if x])
        rec.update(gi_source="2021 International Tables, Suppl. Tables 1+2 (incl. studies with method deviations)",
                   evidence=f"median of {n} tested foods, range {lo:g}-{hi:g}", confidence="medium",
                   citation=CIT_INTL, measured_median=p["recommended"])
    elif p and p["sydney"]:
        s = p["sydney"]
        rec.update(gi_source="University of Sydney online GI database",
                   evidence=f'median of {s["n"]} tested foods, range {s["min"]:g}-{s["max"]:g}',
                   confidence="medium", citation=CIT_SYD, measured_median=s["median"])
    elif gi == 15:
        rec.update(gi_source="Conventional placeholder for foods with too little carbohydrate to test "
                             "(non-starchy vegetables, nuts, seeds, herbs); no published measurement exists",
                   evidence="not measurable", confidence="none (placeholder)", citation="clinical convention")
    else:
        rec.update(gi_source="Estimated from the closest tested food; no direct measurement found in the pooled sources",
                   evidence="no direct match", confidence="low", citation=CIT_INTL + " / " + CIT_SYD)
    if p:
        rec["candidate_from_evidence"] = p["recommended"]
        rec["examples"] = p["examples"][:3]
    out[key] = rec

path = os.path.join(os.path.dirname(__file__), "..", "recipes-db", "gi_sources.py")
with open(path, "w") as fh:
    fh.write('"""Provenance for every GI value in ingredients.py — generated by data/gi-evidence/write_provenance.py.\n'
             'Do not edit by hand: change the matcher or the policy and regenerate."""\n')
    fh.write("GI_SOURCE = " + json.dumps(out, ensure_ascii=False, indent=1) + "\n")
import collections
print("wrote", path)
print(collections.Counter(v["confidence"] for v in out.values()))
